use_frameworks!

platform :ios, '12.0'

target 'Draftsman_Example' do
  pod 'Draftsman', :path => '../'
  pod 'Builder', '~> 1.0.3'

  target 'Draftsman_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 4.0.0'
    pod 'Nimble', '~> 9.2.1'
  end
end
