name: build

on:
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v1
    
    - name: Install Cocoapods
      run: gem install cocoapods
      
    - name: Lib Lint
      run: |
        set -eo pipefail
        pod lib lint --allow-warnings
