name: test

on:
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  test:
    name: Testing Pod
    runs-on: macos-11
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Force XCode 12.5
        run: sudo xcode-select -switch /Applications/Xcode_12.5.app
      - name: Testing Pod Library
        run: bash ./.github/scripts/test_lib.sh